/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Factura.presentation;

import Logic.Producto;
import Logic.Service;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Observable;
import javax.swing.JFrame;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.TableModel;
/**
 *
 * @author David
 */
public class View extends javax.swing.JFrame implements java.util.Observer {

    /** Creates new form View */
    public View() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        int numFac = Service.instance().getSerieFactura();
        jLabel_cifraFactura.setText(String.valueOf(numFac));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_codigoProducto = new javax.swing.JTextField();
        jLabel_Cantidad = new javax.swing.JLabel();
        jTextField_Cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CatalagoProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosFactura = new javax.swing.JTable();
        jButton_BuscarEnCatalogo = new javax.swing.JButton();
        jButton_AgregarAFactura = new javax.swing.JButton();
        jLabel_TituloCatalogo = new javax.swing.JLabel();
        jLabel_tituloFactura = new javax.swing.JLabel();
        jLabel_NombreCliente = new javax.swing.JLabel();
        jTextField_NombreCLiente = new javax.swing.JTextField();
        jLabel_NombreProducto = new javax.swing.JLabel();
        jTextField_NombreProducto = new javax.swing.JTextField();
        jButton_GuardarFACTURA = new javax.swing.JButton();
        jLabel_fechaActual = new javax.swing.JLabel();
        jTextField_FechaActual = new javax.swing.JTextField();
        jLabel_FechaVencimiento = new javax.swing.JLabel();
        jTextField_FechaVencimiento = new javax.swing.JTextField();
        jComboBox_FormaDePago = new javax.swing.JComboBox<>();
        jLabel_FormaPago = new javax.swing.JLabel();
        jLabel_Cambio = new javax.swing.JLabel();
        LABEL_Plazo = new javax.swing.JLabel();
        jComboBox_plazoMeses = new javax.swing.JComboBox<>();
        jLabel_NumeroFACTURA = new javax.swing.JLabel();
        jTextField_TipoCAMBIO = new javax.swing.JTextField();
        jButton_limpiarTodo = new javax.swing.JButton();
        jlaber_errorAgregarFacrtura = new javax.swing.JLabel();
        jlabel_errorBuscarCatalago = new javax.swing.JLabel();
        jLabel_errorGuardarFactura = new javax.swing.JLabel();
        jButton_CargarFecha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        total_etiqueta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoCedula = new javax.swing.JTextField();
        Caja1 = new javax.swing.JCheckBox();
        jLabel_cifraFactura = new javax.swing.JLabel();
        jButton_VaciarFactura = new javax.swing.JButton();
        jLabel_Correo = new javax.swing.JLabel();
        jTextField_Correo = new javax.swing.JTextField();
        jLabel_Ubicacion = new javax.swing.JLabel();
        jTextField_Ubicacion = new javax.swing.JTextField();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_Telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_titulo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1_titulo.setText("Submenu Facturas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo Producto:");

        jTextField_codigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoProductoActionPerformed(evt);
            }
        });

        jLabel_Cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cantidad.setText("Cantidad de productos: ");

        jTextField_Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CantidadActionPerformed(evt);
            }
        });

        CatalagoProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        CatalagoProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalagoProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CatalagoProductos);

        tablaProductosFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaProductosFactura);

        jButton_BuscarEnCatalogo.setText("Buscar en catalogo");
        jButton_BuscarEnCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BuscarEnCatalogoMouseClicked(evt);
            }
        });

        jButton_AgregarAFactura.setText("Agregar a factura ");
        jButton_AgregarAFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AgregarAFacturaMouseClicked(evt);
            }
        });
        jButton_AgregarAFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarAFacturaActionPerformed(evt);
            }
        });

        jLabel_TituloCatalogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_TituloCatalogo.setText("CATALOGO");

        jLabel_tituloFactura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_tituloFactura.setText("FACTURA");

        jLabel_NombreCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NombreCliente.setText("Nombre Cliente: ");

        jTextField_NombreCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreCLienteActionPerformed(evt);
            }
        });

        jLabel_NombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NombreProducto.setText("Nombre del producto:");

        jButton_GuardarFACTURA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_GuardarFACTURA.setText("Guardar Factura");
        jButton_GuardarFACTURA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GuardarFACTURAMouseClicked(evt);
            }
        });

        jLabel_fechaActual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_fechaActual.setText("Fecha Actual: ");

        jTextField_FechaActual.setText("E yyyy/MM/dd HH-mm-ss");
        jTextField_FechaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaActualActionPerformed(evt);
            }
        });

        jLabel_FechaVencimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_FechaVencimiento.setText("Fecha Vencimiento:");

        jTextField_FechaVencimiento.setText("E yyyy/MM/dd HH-mm-ss");
        jTextField_FechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaVencimientoActionPerformed(evt);
            }
        });

        jComboBox_FormaDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02" }));

        jLabel_FormaPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_FormaPago.setText("Forma de Pago:");

        jLabel_Cambio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cambio.setText("Tipo Cambio: ");

        LABEL_Plazo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LABEL_Plazo.setText("Plazo(meses):");

        jComboBox_plazoMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "6", "12" }));

        jLabel_NumeroFACTURA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NumeroFACTURA.setText("No.Factura: ");

        jButton_limpiarTodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_limpiarTodo.setText("Limpiar todo");
        jButton_limpiarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_limpiarTodoMouseClicked(evt);
            }
        });
        jButton_limpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarTodoActionPerformed(evt);
            }
        });

        jlaber_errorAgregarFacrtura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlabel_errorBuscarCatalago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel_errorGuardarFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_errorGuardarFactura.setForeground(new java.awt.Color(255, 51, 51));

        jButton_CargarFecha.setText("Cargar Fecha");
        jButton_CargarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CargarFechaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total: ");

        total_etiqueta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_etiqueta.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cedula Cliente:");

        CampoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoCedulaKeyReleased(evt);
            }
        });

        Caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja1ActionPerformed(evt);
            }
        });

        jLabel_cifraFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cifraFactura.setText("0000");

        jButton_VaciarFactura.setText("Vaciar Factura");
        jButton_VaciarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_VaciarFacturaMouseClicked(evt);
            }
        });

        jLabel_Correo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Correo.setText("Correo:");

        jTextField_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CorreoActionPerformed(evt);
            }
        });

        jLabel_Ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Ubicacion.setText("Ubicacion");

        jLabel_telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_telefono.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_NombreProducto)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_BuscarEnCatalogo)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_errorBuscarCatalago, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_TituloCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_NombreCliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_NombreCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CampoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Caja1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(total_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Correo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Ubicacion)
                                        .addGap(164, 164, 164))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_Cantidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel_tituloFactura)
                                                    .addComponent(jTextField_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton_AgregarAFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_VaciarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel_fechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField_FechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel_FechaVencimiento)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextField_FechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton_CargarFecha)))))
                                .addComponent(jLabel_telefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)
                        .addComponent(jlaber_errorAgregarFacrtura, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Cambio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TipoCAMBIO, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(LABEL_Plazo)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_plazoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_NumeroFACTURA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_cifraFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel_FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_FormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jButton_GuardarFACTURA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_errorGuardarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_limpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_titulo)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NombreProducto)
                            .addComponent(jTextField_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Cantidad)
                            .addComponent(jTextField_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_AgregarAFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel_errorBuscarCatalago, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_TituloCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_BuscarEnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlaber_errorAgregarFacrtura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(CampoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Caja1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NombreCliente)
                                    .addComponent(jTextField_NombreCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Correo)
                                    .addComponent(jTextField_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Ubicacion)
                                    .addComponent(jTextField_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_telefono)
                                    .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_fechaActual)
                                    .addComponent(jTextField_FechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_CargarFecha))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_FechaVencimiento)
                                    .addComponent(jTextField_FechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_VaciarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel_tituloFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(total_etiqueta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cambio)
                    .addComponent(jTextField_TipoCAMBIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_Plazo)
                    .addComponent(jComboBox_plazoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FormaPago)
                    .addComponent(jLabel_NumeroFACTURA)
                    .addComponent(jComboBox_FormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GuardarFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_errorGuardarFactura)
                    .addComponent(jLabel_cifraFactura)
                    .addComponent(jButton_limpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarAFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarAFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AgregarAFacturaActionPerformed

    private void jTextField_CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CantidadActionPerformed

    private void jTextField_NombreCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreCLienteActionPerformed

    private void jButton_AgregarAFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AgregarAFacturaMouseClicked
    try{            
        if (jTextField_codigoProducto.getText().isEmpty() || jTextField_Cantidad.getText().isEmpty()) 
        { 
        Exception i = new Exception();
        throw i;
        }
        else
        {            
            int tam = Integer.parseInt(jTextField_Cantidad.getText());
            for (int i = 0; i < tam; i++) 
            {
            this.controller.agregarProducto(jTextField_codigoProducto.getText()); 
            }
            float valor = this.controller.getTotal();
            String total = String.valueOf(valor);
             jlaber_errorAgregarFacrtura.setText("");
                 total_etiqueta.setText(total);
            this.model.commit();
        }
    }
    catch(Exception ie)
    {
    jlaber_errorAgregarFacrtura.setText("Error");
    }
    }//GEN-LAST:event_jButton_AgregarAFacturaMouseClicked

    private void jTextField_codigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigoProductoActionPerformed

    private void jButton_GuardarFACTURAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GuardarFACTURAMouseClicked
        guardarFactura();
    }//GEN-LAST:event_jButton_GuardarFACTURAMouseClicked

    private void jTextField_FechaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaActualActionPerformed

    private void jButton_BuscarEnCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuscarEnCatalogoMouseClicked
        if (jTextField_NombreProducto.getText().isEmpty()) {
            CatalagoProductos.setModel(new Moldes.ProductoTableModel(Logic.Service.instance().getListaProducto()));
            jlabel_errorBuscarCatalago.setText("");
        }
        else
        {    
       jlabel_errorBuscarCatalago.setText("Error");
       String nameP = jTextField_NombreProducto.getText();
       CatalagoProductos.setModel(new Moldes.ProductoTableModel(Logic.Service.instance().buscarProductosNombre(nameP)));
        }
           
    }//GEN-LAST:event_jButton_BuscarEnCatalogoMouseClicked

    private void jButton_limpiarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_limpiarTodoMouseClicked
        this.ponerTodoEnBlanco();
    }//GEN-LAST:event_jButton_limpiarTodoMouseClicked

    private void jButton_CargarFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CargarFechaMouseClicked
        setFechaActual();
    }//GEN-LAST:event_jButton_CargarFechaMouseClicked

    private void jTextField_FechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaVencimientoActionPerformed

    private void jButton_limpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_limpiarTodoActionPerformed

    private void Caja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caja1ActionPerformed

    private void CampoCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCedulaKeyReleased
        String aux = CampoCedula.getText();
        controller.verificarCliente(aux);
        
    }//GEN-LAST:event_CampoCedulaKeyReleased

    private void jButton_VaciarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_VaciarFacturaMouseClicked
       this.controller.removerProductos();
       this.model.commit();
    }//GEN-LAST:event_jButton_VaciarFacturaMouseClicked

    private void jTextField_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CorreoActionPerformed

    private void CatalagoProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatalagoProductosMouseClicked
       int x = CatalagoProductos.getSelectedRow();
       TableModel model = CatalagoProductos.getModel();
       String Codigo = (String) model.getValueAt(x,2);
       jTextField_codigoProducto.setText(Codigo);
    }//GEN-LAST:event_CatalagoProductosMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Caja1;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTable CatalagoProductos;
    private javax.swing.JLabel LABEL_Plazo;
    private javax.swing.JButton jButton_AgregarAFactura;
    private javax.swing.JButton jButton_BuscarEnCatalogo;
    private javax.swing.JButton jButton_CargarFecha;
    private javax.swing.JButton jButton_GuardarFACTURA;
    private javax.swing.JButton jButton_VaciarFactura;
    private javax.swing.JButton jButton_limpiarTodo;
    private javax.swing.JComboBox<String> jComboBox_FormaDePago;
    private javax.swing.JComboBox<String> jComboBox_plazoMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Cambio;
    private javax.swing.JLabel jLabel_Cantidad;
    private javax.swing.JLabel jLabel_Correo;
    private javax.swing.JLabel jLabel_FechaVencimiento;
    private javax.swing.JLabel jLabel_FormaPago;
    private javax.swing.JLabel jLabel_NombreCliente;
    private javax.swing.JLabel jLabel_NombreProducto;
    private javax.swing.JLabel jLabel_NumeroFACTURA;
    private javax.swing.JLabel jLabel_TituloCatalogo;
    private javax.swing.JLabel jLabel_Ubicacion;
    private javax.swing.JLabel jLabel_cifraFactura;
    private javax.swing.JLabel jLabel_errorGuardarFactura;
    private javax.swing.JLabel jLabel_fechaActual;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JLabel jLabel_tituloFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Cantidad;
    private javax.swing.JTextField jTextField_Correo;
    private javax.swing.JTextField jTextField_FechaActual;
    private javax.swing.JTextField jTextField_FechaVencimiento;
    private javax.swing.JTextField jTextField_NombreCLiente;
    private javax.swing.JTextField jTextField_NombreProducto;
    private javax.swing.JTextField jTextField_Telefono;
    private javax.swing.JTextField jTextField_TipoCAMBIO;
    private javax.swing.JTextField jTextField_Ubicacion;
    private javax.swing.JTextField jTextField_codigoProducto;
    private javax.swing.JLabel jlabel_errorBuscarCatalago;
    private javax.swing.JLabel jlaber_errorAgregarFacrtura;
    private javax.swing.JTable tablaProductosFactura;
    private javax.swing.JLabel total_etiqueta;
    // End of variables declaration//GEN-END:variables

    
   private Controller controller;
    private Factura.presentation.Model model;
    
    public void setController(Controller controller){
        this.controller=controller;
        
    }

    public Controller getController() {
        return controller;
        
    }
    
    public void setNombreCliente(String nombre, String correo, String ubicacion, String telefono){
        jTextField_NombreCLiente.setText(nombre);
        jTextField_Correo.setText(correo);
        jTextField_Ubicacion.setText(ubicacion);
        jTextField_Telefono.setText(telefono);
    }
    
    public void setModel(Factura.presentation.Model model){
        this.model=model;
         model.addObserver(this);
    }

    public Factura.presentation.Model getModel() {
        return model;
    }
    
    public void ponerTodoEnBlanco(){
        jTextField_Cantidad.setText("");
        jTextField_codigoProducto.setText("");
        jTextField_NombreProducto.setText("");
        jTextField_FechaActual.setText("E yyyy/MM/dd HH-mm-ss");
        jTextField_FechaVencimiento.setText("E yyyy/MM/dd HH-mm-ss");
        jTextField_NombreCLiente.setText("");
        jTextField_TipoCAMBIO.setText("");
        CampoCedula.setText("");
        jTextField_Correo.setText("");
        jTextField_Ubicacion.setText("");
        jTextField_Telefono.setText("");
        jLabel_cifraFactura.setText(String.valueOf(Service.instance().getSerieFactura()));
    }
    
     public void limpiarCasillas(){
        jTextField_Cantidad.setText("");
        jTextField_codigoProducto.setText("");
        jTextField_NombreProducto.setText("");
        jTextField_NombreCLiente.setText("");
        jTextField_Correo.setText("");
        jTextField_Ubicacion.setText("");
        jTextField_Telefono.setText("");
    }
    @Override
    public void update(Observable o, Object arg) {
        tablaProductosFactura.setModel(new Moldes.ProductoTableModel(model.getList()));
        CatalagoProductos.setModel(new Moldes.ProductoTableModel(Logic.Service.instance().getListaProducto()));
        
        limpiarCasillas();
        
    }
    
     public void guardarFactura()
    {
    try
    {
     float total = Float.parseFloat(total_etiqueta.getText());   
     jLabel_errorGuardarFactura.setText("");
     int integerFac = Service.instance().getSerieFactura();
     String numFac = String.valueOf(integerFac);
     String fVencimiento = jTextField_FechaVencimiento.getText();
     String fPago = jComboBox_FormaDePago.getSelectedItem().toString();
     String fCreacion = jTextField_FechaActual.getText();
     String nomCliente = jTextField_NombreCLiente.getText();
     String idCliente = CampoCedula.getText();
     String correo = jTextField_Correo.getText();
     String ubi = jTextField_Ubicacion.getText();
     String tel = jTextField_Telefono.getText();
     int plazo = Integer.parseInt(jComboBox_plazoMeses.getSelectedItem().toString());
     float tCambio = Float.parseFloat(jTextField_TipoCAMBIO.getText());  
     
     ///////////////////////////////////////////////////////////////////////
    this.controller.guardarFactura(numFac, fVencimiento, fPago, fCreacion, plazo, tCambio,nomCliente,total, idCliente, correo, ubi, tel);
    jLabel_cifraFactura.setText(String.valueOf(numFac));
    this.tablaProductosFactura.setModel(new Moldes.ProductoTableModel(new ArrayList<Producto>()));
    Service.instance().aumentarSerieFactura();
    this.controller.removerProductos();
    total_etiqueta.setText("0");
    this.ponerTodoEnBlanco();
    //return true;
    }
    catch(Exception ie)
    {
    jLabel_errorGuardarFactura.setText("Error");
    }
    
    }
     
     void cambiarEstadoId(boolean aux){
        Caja1.setSelected(aux);
        
     }
     
     public void setFechaActual()
     {
     Date fechaActual = new Date();
     SimpleDateFormat sdf =  new SimpleDateFormat("E yyyy/MM/dd HH-mm-ss");
     jTextField_FechaActual.setText( sdf.format(fechaActual)); 
     }
}
