/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturas.presentation;

import Logic.Factura;
import Logic.Service;
import Pdf_Factura.pdf_Factura;
import java.util.Observable;
import javax.swing.table.TableModel;
import java.lang.Exception;

/**
 *
 * @author beto
 */
public class View extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CodigoFactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BuscarFacturaCodigo = new javax.swing.JButton();
        LimpiarBotom = new javax.swing.JButton();
        GenerarPDFBotom = new javax.swing.JButton();
        jTextField_pdfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_ErrorGenerarPDF = new javax.swing.JLabel();
        jButton_GenerarXML = new javax.swing.JButton();
        jLabel_XMLError = new javax.swing.JLabel();

        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFacturas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Facturas");

        CodigoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoFacturaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo de la  Factura");

        BuscarFacturaCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuscarFacturaCodigo.setText("BuscarFactura");
        BuscarFacturaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarFacturaCodigoActionPerformed(evt);
            }
        });

        LimpiarBotom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LimpiarBotom.setText("Limpiar Todo");
        LimpiarBotom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarBotomMouseClicked(evt);
            }
        });
        LimpiarBotom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBotomActionPerformed(evt);
            }
        });

        GenerarPDFBotom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GenerarPDFBotom.setText("Generar PDF");
        GenerarPDFBotom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarPDFBotomMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo de Factura para PDF:");

        jLabel_ErrorGenerarPDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_ErrorGenerarPDF.setForeground(new java.awt.Color(255, 0, 0));

        jButton_GenerarXML.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_GenerarXML.setText("Generar XML");
        jButton_GenerarXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GenerarXMLMouseClicked(evt);
            }
        });

        jLabel_XMLError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_XMLError.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_XMLError.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BuscarFacturaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(LimpiarBotom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_GenerarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_pdfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerarPDFBotom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel_ErrorGenerarPDF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_XMLError)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarFacturaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpiarBotom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerarPDFBotom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_pdfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_ErrorGenerarPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_GenerarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_XMLError))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoFacturaActionPerformed

    private void TablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturasMouseClicked
        int x = TablaFacturas.getSelectedRow();
        TableModel model = TablaFacturas.getModel();
        String fact = (String) model.getValueAt(x, 0);
        jTextField_pdfCodigo.setText(fact);
    }//GEN-LAST:event_TablaFacturasMouseClicked

    private void GenerarPDFBotomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarPDFBotomMouseClicked
       try
       {
           if (jTextField_pdfCodigo.getText().isEmpty()) {
               Exception ie = new Exception();
               throw ie;
           }
           else
           {
           String dest = "factura.pdf";
           String codigo = jTextField_pdfCodigo.getText();
           jLabel_ErrorGenerarPDF.setText("");
           pdf_Factura.createPdf(dest, codigo);
           }
       
       }
       catch(Exception ex)
       {
       jLabel_ErrorGenerarPDF.setText("Error");
       }
    }//GEN-LAST:event_GenerarPDFBotomMouseClicked

    private void jButton_GenerarXMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GenerarXMLMouseClicked
        try
       {
           if (jTextField_pdfCodigo.getText().isEmpty()) {
               Exception ie = new Exception();
               throw ie;
           }
           else
           {
           String codigo = jTextField_pdfCodigo.getText();
            Factura facturaEncontrada = Service.instance().buscarIDFactura(codigo);
            Service.instance().storeFac(facturaEncontrada, codigo);
           }
       
       }
       catch(Exception ex)
       {
       jLabel_ErrorGenerarPDF.setText("Error");
       }
    }//GEN-LAST:event_jButton_GenerarXMLMouseClicked

    private void BuscarFacturaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarFacturaCodigoActionPerformed
      Factura filtro = new Factura();
      filtro.setNumeroDeFactura(CodigoFactura.getText());
      controller.buscar(filtro);
        
    }//GEN-LAST:event_BuscarFacturaCodigoActionPerformed

    private void LimpiarBotomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarBotomMouseClicked
        ponerBlanco();
    }//GEN-LAST:event_LimpiarBotomMouseClicked

    private void LimpiarBotomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBotomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LimpiarBotomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarFacturaCodigo;
    private javax.swing.JTextField CodigoFactura;
    private javax.swing.JButton GenerarPDFBotom;
    private javax.swing.JButton LimpiarBotom;
    private javax.swing.JTable TablaFacturas;
    private javax.swing.JButton jButton_GenerarXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_ErrorGenerarPDF;
    private javax.swing.JLabel jLabel_XMLError;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_pdfCodigo;
    // End of variables declaration//GEN-END:variables
     
    
    Model model;
    Controller controller;

    public Model getModel() {
        return model;
    }

    public Controller getController() {
        return controller;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    public void ponerBlanco(){
        CodigoFactura.setText("");
    }
    @Override
    public void update(Observable o, Object o1) {
        TablaFacturas.setModel(new Moldes.FacturasTableModel(model.getList()) );
        
    }

}
